### ISSUE TITLE
Display success message below the submit button

### ISSUE THREAD

**Issue by nitheshhegde** [djangopy-org/ajax_guide#1]
Hi. How do I display the success message right below the Submit button after submitting the form?

**Comment by jai-singhal** [comment]
Hello @nitheshhegde ,
In the success method of AJAX, you can write a simple Javascript/Jquery script to show the content below the submit button
For example

```
...
success : function(response){ 
        ....
	$(HTML SELECTOR).html("Successfully Submitted");
},
...

```
